### ISSUE TITLE
Have a way to add extra parameters to message

### ISSUE THREAD

**Issue by eschava** [NickCis/node-red-contrib-fcm-push-node#2]
Currently only  to/collapseKey/data/notification parameters are supported
According to the Google docs there could be extra parameters, for instance, to specify a priority of the message
Could you please add a way to have any extra parameters in the message?

https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message

**Comment by NickCis** [comment]
Can you list me the parameters that should be added?,

Now a days firebase message is compose in [`src/fcm-push.js`](https://github.com/NickCis/node-red-contrib-fcm-push-node/blob/master/src/fcm-push.js#L11):

```js
        var message = {
          to: msg.payload.to,
          collapse_key: msg.payload.collapseKey,
          notification: msg.payload.notification
        };
```

It's an easy fix, if you want, you can try to send the pr :) (If not, just list the needed parameters and i'll add them)

**Comment by eschava** [comment]
I think the most important ones are:
priority
android
apns
webpush

**Comment by NickCis** [comment]
The problem here is that this node uses [fcm-push](https://github.com/nandarustam/fcm-push) package which uses the [legacy http api](https://firebase.google.com/docs/cloud-messaging/http-server-ref).

The api that you are asking for should use `firebase-admin` which will need a mayor rewrite in order to do the correct authentication with the json service file.  :/

**Comment by eschava** [comment]
Why? Wouldn't it be enough simply copy these properties to the message passed to the fcm-push send method?

**Comment by NickCis** [comment]
Have you read the documentation about the legacy api linked in my previous comment?

**Comment by eschava** [comment]
Yes and haven't found there any restrictions

**Comment by eschava** [comment]
I've added to the fcm-push.js the next line:
`if (msg.payload.priority) message.priority = msg.payload.priority;`
and it definitely works!

**Comment by NickCis** [comment]
Last `0.1.0` version has all the keys: https://www.npmjs.com/package/node-red-contrib-fcm-push-node

**Comment by eschava** [comment]
Thanks a lot!
But I'm afraid that fix contains typos, please recheck it
        if (msg.payload.priority)
          message.data = msg.payload.priority;
should be
        if (msg.payload.priority)
          message.priority= msg.payload.priority;

**Comment by NickCis** [comment]
Check it now please
